amazon:
  associate_id: mrlonelyjtr

error:
  whitelabel:
    enabled: false

management:
  context-path: /management
  security:
    roles: ADMIN

endpoints:
  shutdown:
    enabled: true

---

spring:
  profiles: development

logging:
  level:
    root: debug

---

spring:
  profiles: production

logging:
  file: Logback.log
  level:
    root: warn